#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (g++).
# Generated 10:44:07 AM 22 Feb 2006
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

all:
	(cd ./aiocomport && make -f Makefile.r)
	(cd ./aiofile && make -f Makefile.r)
	(cd ./aiogate && make -f Makefile.r)
	(cd ./aiomsg && make -f Makefile.r)
	(cd ./aiosock && make -f Makefile.r)
	(cd ./alg && make -f Makefile.r)
	(cd ./base && make -f Makefile.r)
	(cd ./crypt && make -f Makefile.r)
	(cd ./daemon && make -f Makefile.r)
	(cd ./db && make -f Makefile.r)
	(cd ./dborcl && make -f Makefile.r)
	(cd ./dbodbc && make -f Makefile.r)
	(cd ./dbmysql && make -f Makefile.r)
	(cd ./fuzzy && make -f Makefile.r)
	(cd ./memdb && make -f Makefile.r)
	(cd ./pcre && make -f Makefile.r)
	(cd ./smart && make -f Makefile.r)
	(cd ./threadpool && make -f Makefile.r)
	(cd ./tokenizer && make -f Makefile.r)
	(cd ./xml && make -f Makefile.r)

clean:
	(cd ./aiocomport && make -f Makefile.r cleanall)
	(cd ./aiofile && make -f Makefile.r cleanall)
	(cd ./aiogate && make -f Makefile.r cleanall)
	(cd ./aiomsg && make -f Makefile.r cleanall)
	(cd ./aiosock && make -f Makefile.r cleanall)
	(cd ./alg && make -f Makefile.r cleanall)
	(cd ./base && make -f Makefile.r cleanall)
	(cd ./crypt && make -f Makefile.r cleanall)
	(cd ./daemon && make -f Makefile.r cleanall)
	(cd ./db && make -f Makefile.r cleanall)
	(cd ./dborcl && make -f Makefile.r cleanall)
	(cd ./dbodbc && make -f Makefile.r cleanall)
	(cd ./dbmysql && make -f Makefile.r cleanall)
	(cd ./fuzzy && make -f Makefile.r cleanall)
	(cd ./memdb && make -f Makefile.r cleanall)
	(cd ./pcre && make -f Makefile.r cleanall)
	(cd ./smart && make -f Makefile.r cleanall)
	(cd ./threadpool && make -f Makefile.r cleanall)
	(cd ./tokenizer && make -f Makefile.r cleanall)
	(cd ./xml && make -f Makefile.r cleanall)
	rm -rf ../output_gcc/release/*

