#=======================================================================
#@V@:Note: File automatically generated by VIDE - 2.00/10Apr03 (g++).
# Generated 10:44:07 AM 22 Feb 2006
# This file regenerated each time you run VIDE, so save under a
#    new name if you hand edit, or it will be overwritten.
#=======================================================================

all:
	(cd ./base && make -f Makefile64.r)
	(cd ./db && make -f Makefile64.r)
	(cd ./odbcdb && make -f Makefile64.r)
	(cd ./net && make -f Makefile64.r)
	(cd ./stargate && make -f Makefile64.r)
	(cd ./trdpool && make -f Makefile64.r)
	(cd ./xml && make -f Makefile64.r)
	(cd ./tokenizer && make -f Makefile64.r)

clean:
	(cd ./base && make -f Makefile64.r cleanall)
	(cd ./db && make -f Makefile64.r cleanall)
	(cd ./odbcdb && make -f Makefile64.r cleanall)
	(cd ./net && make -f Makefile64.r cleanall)
	(cd ./stargate && make -f Makefile64.r cleanall)
	(cd ./trdpool && make -f Makefile64.r cleanall)
	(cd ./xml && make -f Makefile64.r cleanall)
	(cd ./tokenizer && make -f Makefile64.r cleanall)
	rm -rf ../output_gcc/release/*
